version: 2
jobs:
  build: &build
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: dotnet restore
      - run:
          name: Create package
          command: dotnet pack --configuration Release
      - run:
          name: Publish to nuget
          working_directory: /root/project/LimE.Mail.Builders/bin/Release/
          command: dotnet nuget push LimE.Mail.Builders.*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json

workflows:
  version: 2
  "LimE.Mail.Builders":
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - next

